export const routes = [
  {
    name: "Home",
    path: "/home",
    key: "name",
    footer: false,
    header: true,
    profile: false,
    protected: false,
  },
  {
    name: "About us",
    path: "/aboutus",
    key: "aboutUs",
    footer: true,
    header: true,
    profile: false,
    protected: false,
  },
  {
    name: "Contact",
    path: "/contact",
    key: "contact",
    footer: true,
    header: true,
    profile: false,
    protected: false,
  },
  {
    name: "Blog",
    path: "/blog",
    key: "blog",
    footer: true,
    header: true,
    profile: false,
    protected: false,
  },
  {
    name: "Profile",
    path: "/profile",
    key: "profile",
    footer: false,
    header: false,
    profile: true,
    protected: true,
  },
  {
    name: "Dashboard",
    path: "/dashboard",
    key: "dashboard",
    footer: false,
    header: false,
    profile: true,
    protected: true,
  },
  {
    name: "Logout",
    path: "/logout",
    key: "logout",
    footer: false,
    header: false,
    profile: true,
    protected: true,
  },
  {
    name: "Colleges",
    path: "/college",
    key: "college",
    footer: false,
    header: true,
    profile: false,
    protected: true,
  },
  {
    name: "Application",
    path: "/howToApply",
    key: "application",
    footer: false,
    header: true,
    profile: false,
    protected: true,
  },
  {
    name: "Visa",
    path: "/visa",
    key: "visa",
    footer: false,
    header: true,
    profile: false,
    protected: true,
  },
];
